# Generated by Django 5.0.6 on 2024-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=50)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
